<a href="https://colab.research.google.com/github/DhruvGheewala/043_DhruvGheewala/blob/master/Lab1/Lab1_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
li = [1, 2, 3, 4, 5]
array = np.array([1, 2, 3, 4])

print(li)
print(array)
print(type(li))
print(type(array))

print(array + array)
print(li + li)

print(array * 3)
print(li * 3)

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [11]:
mat1 = np.array([array, array, array])
mat2 = np.array([li, li, li])
mat3 = np.array([array, li, li])

print(mat1)
print(mat2)
print(mat3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[array([1, 2, 3, 4]) list([1, 2, 3, 4, 5]) list([1, 2, 3, 4, 5])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


In [12]:
goodMat = np.array([[1, 2], [3, 4]])
print(goodMat)
print(goodMat * 2) # scaled version of goodMat

badMat = np.array([[1, 2, 3], [4, 5, 6], [7, 8]])
print(badMat) # malformed matrix
print(badMat * 2) # It is supposed to scale the whole matrix

result = goodMat * 2 + 1
print(result)

# Add two sum compatible matrices
print(goodMat + goodMat)

# difference vector
print(goodMat - goodMat)

# Multiply each element by itself
print(goodMat * goodMat)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[list([1, 2, 3]) list([4, 5, 6]) list([7, 8])]
[list([1, 2, 3, 1, 2, 3]) list([4, 5, 6, 4, 5, 6]) list([7, 8, 7, 8])]
[[3 5]
 [7 9]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """


In [13]:
mat = np.array([[1, 2], [3, 4], [5, 6]])

print('Original matrix 3 x 2')
print(mat)

print('Transposed matrix 2 x 3')
print(mat.T)

arr = np.array([1, 2, 3, 4])
print('Original array')
print(arr)
print('Transposed array')
print(arr.T)

arr = np.array([[1, 2, 3, 4]])
print('Original array')
print(arr)
print('Transposed array')
print(arr.T)

arr1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(arr1)
print(norm1)

arr2 = np.array([[1, 2], [3, 4]])
norm2 = np.linalg.norm(arr2)
print(norm2)

arr2 = np.array([[1, 1], [2, 2], [3, 3]])
normByCols = np.linalg.norm(arr2, axis = 0)
print(normByCols)

normByRows = np.linalg.norm(arr2, axis = 1)
print(normByRows)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

flavor1 = np.dot(arr1, arr2)
print(flavor1)

flavor2 = np.sum(arr1 * arr2)
print(flavor2)

flavor3 = arr1 @ arr2
print(flavor3)

flavor4 = 0
for a, b in zip(arr1, arr2):
    flavor4 += a * b
print(flavor4)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]
Original array
[1 2 3 4]
Transposed array
[1 2 3 4]
Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]
5.477225575051661
5.477225575051661
[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]
70
70
70
70


In [14]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4]))
norm2 = np.dot([1, 2], [3, 4])
print(norm1, '=', norm2 )

arr2 = np.array([[1, -1], [2, -2], [3, -3]])
sumByCols = np.sum(arr2, axis = 0)
print('Sum by columns: ')
print(sumByCols)

sumByRows = np.sum(arr2, axis = 1)
print('Sum by rows:')
print(sumByRows)

arr2 = np.array([[1, -1], [2, -2], [3, -3]])

mean = np.mean(arr2)
print('Matrix mean: ')
print(mean)

meanByCols = np.mean(arr2, axis = 0)
print('Mean by columns: ')
print(meanByCols)

meanByRows = np.mean(arr2, axis = 1)
print('Mean by rows:')
print(meanByRows)

11 = 11
Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]
Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


In [15]:
arr2 = np.array([[1, 1], [2, 2], [3, 3]])
nparrayCentered = arr2 - np.mean(arr2, axis = 0)

print('Original matrix')
print(arr2)

print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

arr2 = np.array([[1, 3], [2, 4], [3, 5]])
nparrayCentered = arr2.T - np.mean(arr2, axis = 1)
nparrayCentered = nparrayCentered.T

print('Original matrix')
print(arr2)

print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by rows')
print(nparrayCentered.mean(axis = 1))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]
Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


In [16]:
npArray3x2 = np.array([[1, 2, 3], [4, 5, 6]])
npArray2x3 = np.array([[1, 2], [3, 4], [5, 6]])
print(npArray3x2)
print(npArray2x3)

npArray3x2 = np.random.randint(1, 10, size = [3, 2])
npArray2x3 = np.random.randint(1, 10, size = [2, 3])
print(npArray3x2)
print(npArray2x3)

print(np.multiply(npArray3x2, npArray2x3.T))
print(np.multiply(npArray3x2.T, npArray2x3))
print(np.matmul(npArray2x3, npArray3x2))
print(np.matmul(npArray3x2, npArray2x3))
print(np.mean(npArray3x2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[8 7]
 [9 8]
 [8 6]]
[[3 7 2]
 [8 2 7]]
[[24 56]
 [63 16]
 [16 42]]
[[24 63 16]
 [56 16 42]]
[[103  89]
 [138 114]]
[[80 70 65]
 [91 79 74]
 [72 68 58]]
7.666666666666667
