<a href="https://colab.research.google.com/github/DhruvGheewala/043_DhruvGheewala/blob/master/Lab3/Lab3_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import OneHotEncoder

In [6]:
cancer = datasets.load_breast_cancer()
print("Features: ", cancer.feature_names)
print("Labels: ", cancer.target_names)
print("Shape: ", cancer.data.shape)
print("Data: ", cancer.data)
print("Target: ", cancer.target)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels:  ['malignant' 'benign']
Shape:  (569, 30)
Data:  [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0

In [7]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [8]:
# split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(cancer.data, cancer.target, test_size = 0.4, random_state = 26)

gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

print("Accuracy: ", metrics.accuracy_score(target_test, target_pred))
confusion_matrix(target_test, target_pred)

precision = precision_score(target_test, target_pred, average = None)
recall = recall_score(target_test, target_pred, average = None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy:  0.956140350877193
precision: [0.94444444 0.96153846]
recall: [0.91891892 0.97402597]
